### ISSUE TITLE
Add demo

### ISSUE THREAD

**Issue by sheriffderek** [willviles/ember-gsap#1]
Hello. I was just looking for slick ways of getting gsap into projects without any fuss and came across this. With no stars (now 1) - I wasn't really sure if this was complete etc / so I built a little test in ember-twiddle (who has no documentation about using addons) so, _really I was testing addon support - and this addon_... and I made this: https://ember-twiddle.com/f61209fc8ad1f1e85613f8f4ef4573e1

It's nothing great - but maybe you could use it as a starting point for a quick and easy demo and link to it so people can be sure this thing is functional and start using it.  : )

**Comment by willviles** [comment]
Thanks @sheriffderek 👍 

I've added your code as the dummy application for the addon and referenced your Ember Twiddle in the README.

You might like to just modify the twiddle's [application.js](https://ember-twiddle.com/f61209fc8ad1f1e85613f8f4ef4573e1?openFiles=controllers.application.js%2C) to ensure the imports match and jshint unused is satisfied? 

I've done it in the dummy app [here](https://github.com/willviles/ember-gsap/blob/master/tests/dummy/app/controllers/application.js).

**Comment by sheriffderek** [comment]
👍
