### ISSUE TITLE
How to load  `Club GreenSock` plugins 

### ISSUE THREAD

**Issue by teejayhh** [willviles/ember-gsap#12]
We have a  Club GreenSock  membership and would like to load some of the other goodies gsap comes with. Unfortunately I dont see a way to load these with this addon. I guess I have to use the vendor directory to side load them somehow, or do you have a better Idea ??

**Comment by willviles** [comment]
@teejayhh, there's no way this plugin can provide access to Club GreenSock plugins unfortunately. 

I haven't got a license so I can't check the plugins out. However, placing the plugin files in `vendor` and just referencing them like below should work if they're defined as ES6 modules!

```js
import PluginName from 'vendor/club-greensock/plugin-name'
```

Let me know if this works, and if so, we could reference a solution in the README.

**Comment by teejayhh** [comment]
I might not be able to test it today, but I will get to it next week.

**Comment by willviles** [comment]
@teejayhh - just following up on this one. Did you manage to get Club GreenSock plugins working with Ember GSAP?

**Comment by teejayhh** [comment]
I have put up a solution for the problem. Its essentially replicating what you have done here. 

https://greensock.com/forums/topic/17836-import-business-green-plugins-into-ember-app/?tab=comments#comment-81135
