### ISSUE TITLE
Request - Draggable

### ISSUE THREAD

**Issue by dephora** [willviles/ember-gsap#2]
Appreciate the addon, would it be possible to include Draggable as an optional import?

https://greensock.com/draggable

**Comment by willviles** [comment]
Sure @dephora! I won't be able to do this for another week or so. So if you're pressed for this feature, you're very welcome to issue a PR!

**Comment by dephora** [comment]
Great, I'm not exactly pressed for it immediately. If you haven't gotten to it by the time I get to that portion of my rewrite I'll look into adding it. Appreciate it!

**Comment by willviles** [comment]
@dephora, I've added GSAP Draggable plugin support in Ember GSAP `0.2.0`.

Simply add the following to your `config/environment.js`:

```js
ENV['ember-gsap'] = {
  plugins: [
    'draggable'
  ]
};
```
and then you'll be able to import like so:

```js
import { Draggable } from 'gsap';
```

**Comment by dephora** [comment]
Perfect, thanks!
