### ISSUE TITLE
scrollTo

### ISSUE THREAD

**Issue by ralphcrisostomo** [willviles/ember-gsap#9]
ive tried to use scrollTo plugin and follow your instruction but to no avail.

`
  ENV['ember-gsap'] = {
    plugins: [
      'scrollTo'
    ]
  };
`

**Comment by willviles** [comment]
@ralphcrisostomo - can you show me your implementation please? 

I've added a scrollTo test to the dummy app, showing it's working in commit [48f2e08](https://github.com/willviles/ember-gsap/commit/48f2e086086a29c7687a48d385c661e7d54718ff). Take a look!
